### PR TITLE
Hello, Ron. Can you try building it in AOSP M tree? 

### PR DESCRIPTION
**Pull request by agura-lex**
I tried building it in cm-12.1, but it fails. 
BTW, kernel from cm-12.1 branch builds successfully with this commit.

### CODE REVIEW

**Comment by RonGokhale** [comment]
update change as par as Gerrit comment.

**Comment by agura-lex** [comment]
Sorry, I don't understand what do you mean. Do you mean editing the pull request description as it is in commit?

**Comment by agura-lex** [comment]
Oh, I understood. As in Gerrit comment from Andreas Economides. Okay, I will.

**Comment by agura-lex** [comment]
I updated the change. Can you cherry-pick it and build? As in my environment it fails to build M kernel (I ususally build it by 'make bootimage' or 'make recoveryimage')
http://review.cyanogenmod.org/#/c/116659/

**Comment by agura-lex** [comment]
Created pull request with updated commit.

**Pull request closed without merging**
